const ACTIONS_TYPES = {
  // Movies
  // Get all
  GET_MOVIES_ACTION: 'GET_MOVIES_ACTION',
  GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',

  // Create
  POST_MOVIE_ACTION: 'POST_MOVIE_ACTION',
  POST_MOVIE_REQUEST: 'POST_MOVIE_REQUEST',
  POST_MOVIE_SUCCESS: 'POST_MOVIE_SUCCESS',
  POST_MOVIE_ERROR: 'POST_MOVIE_ERROR',
  // Update
  PUT_MOVIE_ACTION: 'PUT_MOVIE_ACTION',
  PUT_MOVIE_REQUEST: 'PUT_MOVIE_REQUEST',
  PUT_MOVIE_SUCCESS: 'PUT_MOVIE_SUCCESS',
  PUT_MOVIE_ERROR: 'PUT_MOVIE_ERROR',
  // Delete
  DELETE_MOVIE_ACTION: 'DELETE_MOVIE_ACTION',
  DELETE_MOVIE_REQUEST: 'DELETE_MOVIE_REQUEST',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',

  //DIRECTORS
  // Get all
  GET_DIRECTORS_ACTION: 'GET_DIRECTORS_ACTION',
  GET_DIRECTORS_REQUEST: 'GET_DIRECTORS_REQUEST',
  GET_DIRECTORS_SUCCESS: 'GET_DIRECTORS_SUCCESS',
  GET_DIRECTORS_ERROR: 'GET_DIRECTORS_ERROR',

  // Create
  POST_DIRECTOR_ACTION: 'POST_DIRECTOR_ACTION',
  POST_DIRECTOR_REQUEST: 'POST_DIRECTOR_REQUEST',
  POST_DIRECTOR_SUCCESS: 'POST_DIRECTOR_SUCCESS',
  POST_DIRECTOR_ERROR: 'POST_DIRECTOR_ERROR',
  // Update
  PUT_DIRECTOR_ACTION: 'PUT_DIRECTOR_ACTION',
  PUT_DIRECTOR_REQUEST: 'PUT_DIRECTOR_REQUEST',
  PUT_DIRECTOR_SUCCESS: 'PUT_DIRECTOR_SUCCESS',
  PUT_DIRECTOR_ERROR: 'PUT_DIRECTOR_ERROR',
  // Delete
  DELETE_DIRECTOR_ACTION: 'DELETE_DIRECTOR_ACTION',
  DELETE_DIRECTOR_REQUEST: 'DELETE_DIRECTOR_REQUEST',
  DELETE_DIRECTOR_SUCCESS: 'DELETE_DIRECTOR_SUCCESS',
  DELETE_DIRECTOR_ERROR: 'DELETE_DIRECTOR_ERROR',

  //ACTORS
  // Get all
  GET_ACTORS_ACTION: 'GET_ACTORS_ACTION',
  GET_ACTORS_REQUEST: 'GET_ACTORS_REQUEST',
  GET_ACTORS_SUCCESS: 'GET_ACTORS_SUCCESS',
  GET_ACTORS_ERROR: 'GET_ACTORS_ERROR',
  ///

  // Create
  POST_ACTOR_ACTION: 'POST_ACTOR_ACTION',
  POST_ACTOR_REQUEST: 'POST_ACTOR_REQUEST',
  POST_ACTOR_SUCCESS: 'POST_ACTOR_SUCCESS',
  POST_ACTOR_ERROR: 'POST_ACTOR_ERROR',
  // Update
  PUT_ACTOR_ACTION: 'PUT_ACTOR_ACTION',
  PUT_ACTOR_REQUEST: 'PUT_ACTOR_REQUEST',
  PUT_ACTOR_SUCCESS: 'PUT_ACTOR_SUCCESS',
  PUT_ACTOR_ERROR: 'PUT_ACTOR_ERROR',
  // Delete
  DELETE_ACTOR_ACTION: 'DELETE_ACTOR_ACTION',
  DELETE_ACTOR_REQUEST: 'DELETE_ACTOR_REQUEST',
  DELETE_ACTOR_SUCCESS: 'DELETE_ACTOR_SUCCESS',
  DELETE_ACTOR_ERROR: 'DELETE_ACTOR_ERROR',

  //

  // --------------------------------

  //MOVIES_BY_ACTOR
  GET_MOVIES_BY_ACTOR_ACTION: 'GET_MOVIES_BY_ACTOR_ACTION',
  GET_MOVIES_BY_ACTOR_REQUEST: 'GET_MOVIES_BY_ACTOR_REQUEST',
  GET_MOVIES_BY_ACTOR_SUCCESS: 'GET_MOVIES_BY_ACTOR_SUCCESS',
  GET_MOVIES_BY_ACTOR_ERROR: 'GET_MOVIES_BY_ACTOR_ERROR',

  POST_MOVIE_BY_ACTOR_ACTION: 'POST_MOVIE_BY_ACTOR_ACTION',
  POST_MOVIE_BY_ACTOR_REQUEST: 'POST_MOVIE_BY_ACTOR_REQUEST',
  POST_MOVIE_BY_ACTOR_SUCCESS: 'POST_MOVIE_BY_ACTOR_SUCCESS',
  POST_MOVIE_BY_ACTOR_ERROR: 'POST_MOVIE_BY_ACTOR_ERROR',

  DELETE_MOVIE_BY_ACTOR_ACTION: 'DELETE_MOVIE_BY_ACTOR_ACTION',
  DELETE_MOVIE_BY_ACTOR_REQUEST: 'DELETE_MOVIE_BY_ACTOR_REQUEST',
  DELETE_MOVIE_BY_ACTOR_SUCCESS: 'DELETE_MOVIE_BY_ACTOR_SUCCESS',
  DELETE_MOVIE_BY_ACTOR_ERROR: 'DELETE_MOVIE_BY_ACTOR_ERROR',

  //MOVIES_BY_DIRECTOR
  GET_MOVIES_BY_DIRECTOR_ACTION: 'GET_MOVIES_BY_DIRECTOR_ACTION',
  GET_MOVIES_BY_DIRECTOR_REQUEST: 'GET_MOVIES_BY_DIRECTOR_REQUEST',
  GET_MOVIES_BY_DIRECTOR_SUCCESS: 'GET_MOVIES_BY_DIRECTOR_SUCCESS',
  GET_MOVIES_BY_DIRECTOR_ERROR: 'GET_MOVIES_BY_DIRECTOR_ERROR',

  POST_MOVIE_BY_DIRECTOR_ACTION: 'POST_MOVIE_BY_DIRECTOR_ACTION',
  POST_MOVIE_BY_DIRECTOR_REQUEST: 'POST_MOVIE_BY_DIRECTOR_REQUEST',
  POST_MOVIE_BY_DIRECTOR_SUCCESS: 'POST_MOVIE_BY_DIRECTOR_SUCCESS',
  POST_MOVIE_BY_DIRECTOR_ERROR: 'POST_MOVIE_BY_DIRECTOR_ERROR',

  DELETE_MOVIE_BY_DIRECTOR_ACTION: 'DELETE_MOVIE_BY_DIRECTOR_ACTION',
  DELETE_MOVIE_BY_DIRECTOR_REQUEST: 'DELETE_MOVIE_BY_DIRECTOR_REQUEST',
  DELETE_MOVIE_BY_DIRECTOR_SUCCESS: 'DELETE_MOVIE_BY_DIRECTOR_SUCCESS',
  DELETE_MOVIE_BY_DIRECTOR_ERROR: 'DELETE_MOVIE_BY_DIRECTOR_ERROR',

  // --------------------------------

  // --------------------------------
  //DIRECTORS_ACTORS_BY_MOVIES

  //ACTORS_BY_MOVIE
  GET_ACTORS_BY_MOVIE_ACTION: 'GET_ACTORS_BY_MOVIE_ACTION',
  GET_ACTORS_BY_MOVIE_REQUEST: 'GET_ACTORS_BY_MOVIE_REQUEST',
  GET_ACTORS_BY_MOVIE_SUCCESS: 'GET_ACTORS_BY_MOVIE_SUCCESS',
  GET_ACTORS_BY_MOVIE_ERROR: 'GET_ACTORS_BY_MOVIE_ERROR',

  POST_ACTOR_BY_MOVIE_ACTION: 'POST_ACTOR_BY_MOVIE_ACTION',
  POST_ACTOR_BY_MOVIE_REQUEST: 'POST_ACTOR_BY_MOVIE_REQUEST',
  POST_ACTOR_BY_MOVIE_SUCCESS: 'POST_ACTOR_BY_MOVIE_SUCCESS',
  POST_ACTOR_BY_MOVIE_ERROR: 'POST_ACTOR_BY_MOVIE_ERROR',

  DELETE_ACTOR_BY_MOVIE_ACTION: 'DELETE_ACTOR_BY_MOVIE_ACTION',
  DELETE_ACTOR_BY_MOVIE_REQUEST: 'DELETE_ACTOR_BY_MOVIE_REQUEST',
  DELETE_ACTOR_BY_MOVIE_SUCCESS: 'DELETE_ACTOR_BY_MOVIE_SUCCESS',
  DELETE_ACTOR_BY_MOVIE_ERROR: 'DELETE_ACTOR_BY_MOVIE_ERROR',

  //DIRECTORS_BY_MOVIE
  GET_DIRECTORS_BY_MOVIE_ACTION: 'GET_DIRECTORS_BY_MOVIE_ACTION',
  GET_DIRECTORS_BY_MOVIE_REQUEST: 'GET_DIRECTORS_BY_MOVIE_REQUEST',
  GET_DIRECTORS_BY_MOVIE_SUCCESS: 'GET_DIRECTORS_BY_MOVIE_SUCCESS',
  GET_DIRECTORS_BY_MOVIE_ERROR: 'GET_DIRECTORS_BY_MOVIE_ERROR',

  POST_DIRECTOR_BY_MOVIE_ACTION: 'POST_DIRECTOR_BY_MOVIE_ACTION',
  POST_DIRECTOR_BY_MOVIE_REQUEST: 'POST_DIRECTOR_BY_MOVIE_REQUEST',
  POST_DIRECTOR_BY_MOVIE_SUCCESS: 'POST_DIRECTOR_BY_MOVIE_SUCCESS',
  POST_DIRECTOR_BY_MOVIE_ERROR: 'POST_DIRECTOR_BY_MOVIE_ERROR',

  DELETE_DIRECTOR_BY_MOVIE_ACTION: 'DELETE_DIRECTOR_BY_MOVIE_ACTION',
  DELETE_DIRECTOR_BY_MOVIE_REQUEST: 'DELETE_DIRECTOR_BY_MOVIE_REQUEST',
  DELETE_DIRECTOR_BY_MOVIE_SUCCESS: 'DELETE_DIRECTOR_BY_MOVIE_SUCCESS',
  DELETE_DIRECTOR_BY_MOVIE_ERROR: 'DELETE_DIRECTOR_BY_MOVIE_ERROR',

  // --------------------------------
  //STUDIOS
  // Get all
  GET_STUDIOS_ACTION: 'GET_STUDIOS_ACTION',
  GET_STUDIOS_REQUEST: 'GET_STUDIOS_REQUEST',
  GET_STUDIOS_SUCCESS: 'GET_STUDIOS_SUCCESS',
  GET_STUDIOS_ERROR: 'GET_STUDIOS_ERROR',

  // Create
  POST_STUDIO_ACTION: 'POST_STUDIO_ACTION',
  POST_STUDIO_REQUEST: 'POST_STUDIO_REQUEST',
  POST_STUDIO_SUCCESS: 'POST_STUDIO_SUCCESS',
  POST_STUDIO_ERROR: 'POST_STUDIO_ERROR',
  // Update
  PUT_STUDIO_ACTION: 'PUT_STUDIO_ACTION',
  PUT_STUDIO_REQUEST: 'PUT_STUDIO_REQUEST',
  PUT_STUDIO_SUCCESS: 'PUT_STUDIO_SUCCESS',
  PUT_STUDIO_ERROR: 'PUT_STUDIO_ERROR',
  // Delete
  DELETE_STUDIO_ACTION: 'DELETE_STUDIO_ACTION',
  DELETE_STUDIO_REQUEST: 'DELETE_STUDIO_REQUEST',
  DELETE_STUDIO_SUCCESS: 'DELETE_STUDIO_SUCCESS',
  DELETE_STUDIO_ERROR: 'DELETE_STUDIO_ERROR',

  //GENRES
  //Get ALL
  GET_GENRES_ACTION: 'GET_GENRES_ACTION',
  GET_GENRES_REQUEST: 'GET_GENRES_REQUEST',
  GET_GENRES_SUCCESS: 'GET_GENRES_SUCCESS',
  GET_GENRES_ERROR: 'GET_GENRES_ERROR',
  //CREATE
  POST_GENRE_ACTION: 'POST_GENRE_ACTION',
  POST_GENRE_REQUEST: 'POST_GENRE_REQUEST',
  POST_GENRE_SUCCESS: 'POST_GENRE_SUCCESS',
  POST_GENRE_ERROR: 'POST_GENRE_ERROR',
  //update
  PUT_GENRE_ACTION: 'PUT_GENRE_ACTION',
  PUT_GENRE_REQUEST: 'PUT_GENRE_REQUEST',
  PUT_GENRE_SUCCESS: 'PUT_GENRE_SUCCESS',
  PUT_GENRE_ERROR: 'PUT_GENRE_ERROR',
  //Delete
  DELETE_GENRE_ACTION: 'DELETE_GENRE_ACTION',
  DELETE_GENRE_REQUEST: 'DELETE_GENRE_REQUEST',
  DELETE_GENRE_SUCCESS: 'DELETE_GENRE_SUCCESS',
  DELETE_GENRE_ERROR: 'DELETE_GENRE_ERROR',

  //Nationalities
  //Get ALL
  GET_NATIONALITIES_ACTION: 'GET_NATIONALITIES_ACTION',
  GET_NATIONALITIES_REQUEST: 'GET_NATIONALITIES_REQUEST',
  GET_NATIONALITIES_SUCCESS: 'GET_NATIONALITIES_SUCCESS',
  GET_NATIONALITIES_ERROR: 'GET_NATIONALITIES_ERROR',
  //CREATE
  POST_NATIONALITY_ACTION: 'POST_NATIONALITY_ACTION',
  POST_NATIONALITY_REQUEST: 'POST_NATIONALITY_REQUEST',
  POST_NATIONALITY_SUCCESS: 'POST_NATIONALITY_SUCCESS',
  POST_NATIONALITY_ERROR: 'POST_NATIONALITY_ERROR',
  //update
  PUT_NATIONALITY_ACTION: 'PUT_NATIONALITY_ACTION',
  PUT_NATIONALITY_REQUEST: 'PUT_NATIONALITY_REQUEST',
  PUT_NATIONALITY_SUCCESS: 'PUT_NATIONALITY_SUCCESS',
  PUT_NATIONALITY_ERROR: 'PUT_NATIONALITY_ERROR',
  //Delete
  DELETE_NATIONALITY_ACTION: 'DELETE_NATIONALITY_ACTION',
  DELETE_NATIONALITY_REQUEST: 'DELETE_NATIONALITY_REQUEST',
  DELETE_NATIONALITY_SUCCESS: 'DELETE_NATIONALITY_SUCCESS',
  DELETE_NATIONALITY_ERROR: 'DELETE_NATIONALITY_ERROR',

  //LOCATION
  // GET by country
  GET_LOCATIONS_ACTION: 'GET_LOCATIONS_ACTION',
  GET_LOCATIONS_REQUEST: 'GET_LOCATIONS_REQUEST',
  GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
  GET_LOCATIONS_ERROR: 'GET_LOCATIONS_ERROR',
  //CREATE
  POST_LOCATION_ACTION: 'POST_LOCATION_ACTION',
  POST_LOCATION_REQUEST: 'POST_LOCATION_REQUEST',
  POST_LOCATION_SUCCESS: 'POST_LOCATION_SUCCESS',
  POST_LOCATION_ERROR: 'POST_LOCATION_ERROR',
  //update
  PUT_LOCATION_ACTION: 'PUT_LOCATION_ACTION',
  PUT_LOCATION_REQUEST: 'PUT_LOCATION_REQUEST',
  PUT_LOCATION_SUCCESS: 'PUT_LOCATION_SUCCESS',
  PUT_LOCATION_ERROR: 'PUT_LOCATION_ERROR',
  //Delete
  DELETE_LOCATION_ACTION: 'DELETE_LOCATION_ACTION',
  DELETE_LOCATION_REQUEST: 'DELETE_LOCATION_REQUEST',
  DELETE_LOCATION_SUCCESS: 'DELETE_LOCATION_SUCCESS',
  DELETE_LOCATION_ERROR: 'DELETE_LOCATION_ERROR',
}

export default ACTIONS_TYPES
